# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-165379372-1'

menu:
- {name: 'Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Internships', folder: 'pages', file: 'internships.html'}
- {name: 'F. Student', folder: 'pages', file: 'formulastudent.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/vasco-breitenfeld/'}
- {icon: 'envelope', link: 'mailto:vascobreitenfeld99@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
